tasks:
 - tox -e py27-django18
 - tox -e py27-django19
 - tox -e py34-django18
 - tox -e py34-django19
 - tox -e py35-django19
 - tox -e py34-django110
 - tox -e py35-django110
 - tox -e flake8
 - tox -e isort
 - tox -e coverage
 - tox -e docs

services:
  - postgresql

coverage:
  path: coverage.xml
  parser: python
